name = "RigorousCoupledWaveAnalysis"
uuid = "c8f76c1c-e1da-11e9-2f58-db462fa08db6"
authors = ["jonschlipf <schlipf.jon@gmx.net>"]
version = "1.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
CSV = ">=0.8"
DataFrames = ">=0.22"
FFTW = ">=1"
Interpolations = ">=0.13"
SpecialFunctions = ">=1"
julia = ">=1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
